export interface CameraWaypoint {
  id: string;
  position: [number, number, number];
  target: [number, number, number];
  fov: number;
  shakeIntensity: number;
  bloomIntensity: number;
  chromaticAberrationOffset: number;
  focusDistance: number;
  aperture: number;
}

export const CAMERA_WAYPOINTS: CameraWaypoint[] = [
  {
    id: "loading",
    position: [0, 0, 8],
    target: [0, 0, 0],
    fov: 45,
    shakeIntensity: 1.2,
    bloomIntensity: 2.0,
    chromaticAberrationOffset: 0.005,
    focusDistance: 8.0,
    aperture: 0.08,
  },
  {
    id: "hero",
    position: [0, 0, 10],
    target: [0, 0, 0],
    fov: 45,
    shakeIntensity: 0.5,
    bloomIntensity: 1.0,
    chromaticAberrationOffset: 0.002,
    focusDistance: 10.0,
    aperture: 0.02,
  },
  {
    id: "digital-hq",
    position: [4, 1.5, 8],
    target: [1, 0, 0],
    fov: 45,
    shakeIntensity: 0.3,
    bloomIntensity: 0.8,
    chromaticAberrationOffset: 0.001,
    focusDistance: 8.5,
    aperture: 0.015,
  },
  {
    id: "web-dev",
    position: [-4.5, 3.5, 6],
    target: [-1.5, 0.5, 0],
    fov: 45,
    shakeIntensity: 0.4,
    bloomIntensity: 0.9,
    chromaticAberrationOffset: 0.0015,
    focusDistance: 7.0,
    aperture: 0.02,
  },
  {
    id: "mobile-app",
    position: [0, 8, 3.5],
    target: [0, 0, 0],
    fov: 42,
    shakeIntensity: 0.2,
    bloomIntensity: 0.7,
    chromaticAberrationOffset: 0.001,
    focusDistance: 8.5,
    aperture: 0.012,
  },
  {
    id: "ai",
    position: [5, -2, 5],
    target: [0, 0, -2],
    fov: 40,
    shakeIntensity: 0.8,
    bloomIntensity: 1.5,
    chromaticAberrationOffset: 0.003,
    focusDistance: 7.5,
    aperture: 0.025,
  },
  {
    id: "cloud-infra",
    position: [-6, 6, -6],
    target: [0, 0, 0],
    fov: 45,
    shakeIntensity: 0.3,
    bloomIntensity: 0.6,
    chromaticAberrationOffset: 0.001,
    focusDistance: 10.0,
    aperture: 0.01,
  },
  {
    id: "crm",
    position: [7, 0.5, 3],
    target: [1, 0, -1],
    fov: 45,
    shakeIntensity: 0.4,
    bloomIntensity: 0.7,
    chromaticAberrationOffset: 0.0015,
    focusDistance: 7.5,
    aperture: 0.015,
  },
  {
    id: "cyber-sec",
    position: [0, 4, 12],
    target: [0, 1, 0],
    fov: 45,
    shakeIntensity: 0.6,
    bloomIntensity: 1.1,
    chromaticAberrationOffset: 0.002,
    focusDistance: 12.0,
    aperture: 0.02,
  },
  {
    id: "it-infra",
    position: [-8, -2, 8],
    target: [-2, 0, 0],
    fov: 45,
    shakeIntensity: 0.5,
    bloomIntensity: 0.7,
    chromaticAberrationOffset: 0.0012,
    focusDistance: 11.0,
    aperture: 0.018,
  },
  {
    id: "contact",
    position: [0, 0, 6],
    target: [0, 0, 0],
    fov: 45,
    shakeIntensity: 0.2,
    bloomIntensity: 0.6,
    chromaticAberrationOffset: 0.001,
    focusDistance: 6.0,
    aperture: 0.008,
  },
];
