export interface StoryState {
  aiCoreScale: number;
  aiCoreColor: string;
  aiCoreShape: "sphere" | "cube" | "neural" | "shield" | "device";
  lightIntensity: number;
  lightColor: string;
  particlesCount: number;
  particlesSpeed: number;
  uiTitle: {
    en: string;
    de: string;
    fr: string;
  };
  uiSubtitle: {
    en: string;
    de: string;
    fr: string;
  };
}

export interface StoryNode {
  id: string;
  name: string;
  states: {
    entry: StoryState;
    focus: StoryState;
    interaction: StoryState;
    exit: StoryState;
  };
  branches: {
    default: string;
    alternative?: string;
  };
}

// Global Story Timeline Configuration mapping all 11 cinematic worlds
export const STORY_TIMELINE: StoryNode[] = [
  {
    id: "loading",
    name: "System Loading",
    branches: { default: "hero" },
    states: {
      entry: {
        aiCoreScale: 0.1,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 0.1,
        lightColor: "#ffffff",
        particlesCount: 20,
        particlesSpeed: 0.5,
        uiTitle: { en: "ALIGNING CORE STRUCTURE", de: "KERNSTRUKTUR AUSRICHTEN", fr: "ALIGNEMENT DU NOYAU" },
        uiSubtitle: { en: "Assembling core neural array...", de: "Kern-Array wird zusammengesetzt...", fr: "Assemblage du réseau neuronal..." },
      },
      focus: {
        aiCoreScale: 0.4,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 0.4,
        lightColor: "#ffffff",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "VALIDATING OPTICAL PATHS", de: "OPTISCHE WEGE VALIDIEREN", fr: "VALIDATION DES VOIES OPTIQUES" },
        uiSubtitle: { en: "Calibrating optical telemetry nodes...", de: "Optische Telemetrieknoten werden kalibriert...", fr: "Calibrage des nœuds optiques..." },
      },
      interaction: {
        aiCoreScale: 0.6,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 0.6,
        lightColor: "#ffffff",
        particlesCount: 80,
        particlesSpeed: 1.5,
        uiTitle: { en: "COGNITIVE ARRAY LOCKED", de: "KOGNITIVES ARRAY VERRIEGELT", fr: "RÉSEAU COGNITIF VERROUILLÉ" },
        uiSubtitle: { en: "Telemetry channels active. Ready to initiate.", de: "Telemetriekanäle aktiv. Bereit zur Initiierung.", fr: "Voies actives. Prêt à démarrer." },
      },
      exit: {
        aiCoreScale: 0.8,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 0.8,
        lightColor: "#ffffff",
        particlesCount: 100,
        particlesSpeed: 2.0,
        uiTitle: { en: "ENGAGING PROTOCOLS", de: "PROTOKOLLE AKTIVIEREN", fr: "ACTIVATION DES PROTOCOLES" },
        uiSubtitle: { en: "Transitioning to environment...", de: "Übergang zur Umgebung...", fr: "Transition vers l'environnement..." },
      },
    },
  },
  {
    id: "hero",
    name: "Hero Experience",
    branches: { default: "digital-hq" },
    states: {
      entry: {
        aiCoreScale: 1.0,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#ffffff",
        particlesCount: 30,
        particlesSpeed: 0.8,
        uiTitle: { en: "DIGITAL ECOSYSTEMS, REALIZED.", de: "DIGITALE ÖKOSYSTEME, REALISIERT.", fr: "ÉCOSYSTEMES NUMÉRIQUES, RÉALISÉS." },
        uiSubtitle: { en: "We design and build clean, high-utility digital architecture. Systems engineered with absolute purpose.", de: "Wir entwerfen und bauen saubere, hochfunktionelle digitale Architektur. Systeme, die mit absolutem Sinn entwickelt wurden.", fr: "Nous concevons des architectures numériques épurées et à haute utilité. Des systèmes conçus avec un but absolu." },
      },
      focus: {
        aiCoreScale: 1.2,
        aiCoreColor: "#f5f5f7",
        aiCoreShape: "sphere",
        lightIntensity: 1.2,
        lightColor: "#f5f5f7",
        particlesCount: 50,
        particlesSpeed: 1.0,
        uiTitle: { en: "ENGINEERED FOR SCALE.", de: "FÜR SKALIERUNG ENTWICKELT.", fr: "CONÇU POUR L'ÉCHELLE." },
        uiSubtitle: { en: "Timeless architectures designed to absorb complexity and drive permanent execution speed.", de: "Zeitlose Architekturen, die darauf ausgelegt sind, Komplexität zu absorbieren und permanente Ausführungsgeschwindigkeit zu liefern.", fr: "Des architectures intemporelles conçues pour absorber la complexité et offrir une vitesse d'exécution permanente." },
      },
      interaction: {
        aiCoreScale: 1.4,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.4,
        lightColor: "#ffffff",
        particlesCount: 60,
        particlesSpeed: 1.2,
        uiTitle: { en: "ENGAGE SYSTEM PROTOCOL.", de: "SYSTEMPROTOKOLL AKTIVIEREN.", fr: "ACTIVER LE PROTOCOLE SYSTÈME." },
        uiSubtitle: { en: "Scrub scroll tracks or adjust perspective viewpoints to dissect structural components.", de: "Scrollen Sie durch Pfade oder passen Sie die Perspektive an, um strukturelle Komponenten zu analysieren.", fr: "Parcourez les axes ou ajustez les angles de vue pour disséquer les composants structurels." },
      },
      exit: {
        aiCoreScale: 1.0,
        aiCoreColor: "#e5e5eb",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#e5e5eb",
        particlesCount: 30,
        particlesSpeed: 0.8,
        uiTitle: { en: "DESCENDING TO HQ PATH.", de: "ABSTIEG ZUM HQ-PFAD.", fr: "DESCENTE VERS LE QG." },
        uiSubtitle: { en: "Connecting structural bridges and loading data highway meshes...", de: "Strukturelle Brücken verbinden und Datenautobahnen laden...", fr: "Connexion des ponts structurels et chargement des réseaux de données..." },
      },
    },
  },
  {
    id: "digital-hq",
    name: "Digital Headquarters",
    branches: { default: "website-development", alternative: "artificial-intelligence" },
    states: {
      entry: {
        aiCoreScale: 1.2,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.2,
        lightColor: "#ffffff",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "DIGITAL HEADQUARTERS.", de: "DIGITALES HAUPTQUARTIER.", fr: "SIÈGE NUMÉRIQUE." },
        uiSubtitle: { en: "A blueprint of functional complexity. Glass columns, digital routes, and autonomous traffic, synchronized.", de: "Eine Blaupause funktionaler Komplexität. Glassäulen, digitale Routen und autonomer Verkehr, synchronisiert.", fr: "Un plan de complexité fonctionnelle. Colonnes de verre, voies numériques et trafic autonome, synchronisés." },
      },
      focus: {
        aiCoreScale: 1.4,
        aiCoreColor: "#f0f0f5",
        aiCoreShape: "sphere",
        lightIntensity: 1.4,
        lightColor: "#f0f0f5",
        particlesCount: 60,
        particlesSpeed: 1.2,
        uiTitle: { en: "INTELLIGENT INTEGRATION.", de: "INTELLIGENTE INTEGRATION.", fr: "INTEGRATION INTELLIGENTE." },
        uiSubtitle: { en: "Data pipelines streaming beneath glass beds, feeding active processing nodes continuously.", de: "Datenpipelines, die unter Glasbetten fließen und aktive Verarbeitungsknoten kontinuierlich speisen.", fr: "Des flux de données circulant sous le verre, alimentant en continu les nœuds de traitement actifs." },
      },
      interaction: {
        aiCoreScale: 1.5,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.5,
        lightColor: "#ffffff",
        particlesCount: 80,
        particlesSpeed: 1.5,
        uiTitle: { en: "SELECT TIMELINE BRANCH.", de: "ZEITLEITUNGSZWEIG WÄHLEN.", fr: "SÉLECTIONNER L'AXE." },
        uiSubtitle: { en: "Select linear track grid or switch to neural branch pathway in header selector.", de: "Wählen Sie das lineare Raster oder wechseln Sie im Header-Wähler zum neuralen Pfad.", fr: "Sélectionnez l'axe linéaire ou basculez vers le parcours neuronal dans le sélecteur." },
      },
      exit: {
        aiCoreScale: 1.1,
        aiCoreColor: "#dddddf",
        aiCoreShape: "cube",
        lightIntensity: 1.0,
        lightColor: "#dddddf",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "MORPHING ARCHITECTURE.", de: "ARCHITEKTUR-MORPHING.", fr: "MORPHISME DE STRUCTURE." },
        uiSubtitle: { en: "Rebuilding nodes to code grids and structural frameworks...", de: "Knotenpunkte zu Codegittern und strukturellen Rahmen umbauen...", fr: "Reconfiguration des nœuds vers les grilles de code..." },
      },
    },
  },
  {
    id: "website-development",
    name: "Web Development",
    branches: { default: "mobile-applications" },
    states: {
      entry: {
        aiCoreScale: 1.1,
        aiCoreColor: "#ffffff",
        aiCoreShape: "cube",
        lightIntensity: 1.1,
        lightColor: "#ffffff",
        particlesCount: 30,
        particlesSpeed: 0.8,
        uiTitle: { en: "FUNCTIONAL LAYERS.", de: "FUNKTIONALE EBENEN.", fr: "COUCHES FONCTIONNELLES." },
        uiSubtitle: { en: "Web platforms treated as engineering structures. Clean execution, minimal bundle weights, permanent speed.", de: "Webplattformen als technische Strukturen behandelt. Saubere Ausführung, minimale Bündelgewichte, dauerhafte Geschwindigkeit.", fr: "Plates-formes web traitées comme des structures d'ingénierie. Exécution propre, poids légers, vitesse permanente." },
      },
      focus: {
        aiCoreScale: 1.3,
        aiCoreColor: "#ffffff",
        aiCoreShape: "cube",
        lightIntensity: 1.3,
        lightColor: "#ffffff",
        particlesCount: 50,
        particlesSpeed: 1.0,
        uiTitle: { en: "CLINICAL EXECUTION.", de: "KLINISCHE AUSFÜHRUNG.", fr: "EXÉCUTION CLINIQUE." },
        uiSubtitle: { en: "Functional, zero-overhead templates compiled cleanly under Next.js server topologies.", de: "Funktionale Vorlagen ohne Overhead, sauber kompiliert unter Next.js-Serverstopologien.", fr: "Gabarits fonctionnels sans surcharge, compilés proprement sous les topologies de serveur Next.js." },
      },
      interaction: {
        aiCoreScale: 1.5,
        aiCoreColor: "#ffffff",
        aiCoreShape: "cube",
        lightIntensity: 1.5,
        lightColor: "#ffffff",
        particlesCount: 70,
        particlesSpeed: 1.3,
        uiTitle: { en: "DIAGNOSTIC TELEMETRY.", de: "DIAGNOSTISCHE TELEMETRIE.", fr: "TÉLÉMÉTRIE DIAGNOSTIQUE." },
        uiSubtitle: { en: "Inspect assembly arrays and verify code weight distributions live.", de: "Überprüfen Sie Montage-Arrays und verifizieren Sie die Code-Gewichtsverteilung live.", fr: "Inspectez les tableaux d'assemblage et vérifiez la répartition des poids du code en direct." },
      },
      exit: {
        aiCoreScale: 1.0,
        aiCoreColor: "#e0e0e0",
        aiCoreShape: "device",
        lightIntensity: 1.0,
        lightColor: "#e0e0e0",
        particlesCount: 30,
        particlesSpeed: 0.8,
        uiTitle: { en: "TRANSITION TO HANDHELD.", de: "ÜBERGANG ZU HANDHELD.", fr: "TRANSITION VERS LE PORTABLE." },
        uiSubtitle: { en: "Assembling holographic device frame nodes...", de: "Holographische Geräterahmenknoten werden zusammengebaut...", fr: "Assemblage des nœuds d'affichage holographique..." },
      },
    },
  },
  {
    id: "mobile-applications",
    name: "Mobile Applications",
    branches: { default: "artificial-intelligence" },
    states: {
      entry: {
        aiCoreScale: 1.0,
        aiCoreColor: "#ffffff",
        aiCoreShape: "device",
        lightIntensity: 1.0,
        lightColor: "#ffffff",
        particlesCount: 30,
        particlesSpeed: 0.8,
        uiTitle: { en: "HANDHELD VIEWS.", de: "HANDHELD ANSICHTEN.", fr: "VUES PORTABLES." },
        uiSubtitle: { en: "Responsive grids optimized for native viewports. Seamless synchronization across distributed client frames.", de: "Responsive Raster, optimiert für native Viewports. Nahtlose Synchronisation über verteilte Client-Frames.", fr: "Grilles réactives optimisées pour les fenêtres natives. Synchronisation transparente sur les cadres clients distribués." },
      },
      focus: {
        aiCoreScale: 1.2,
        aiCoreColor: "#f5f5f7",
        aiCoreShape: "device",
        lightIntensity: 1.2,
        lightColor: "#f5f5f7",
        particlesCount: 50,
        particlesSpeed: 1.0,
        uiTitle: { en: "NATIVE INTEGRITY.", de: "NATIVE INTEGRITÄT.", fr: "INTÉGRITÉ NATIVE." },
        uiSubtitle: { en: "Compiled client frameworks designed to resolve state changes without UI latency.", de: "Kompilierte Client-Frameworks, die darauf ausgelegt sind, Statusänderungen ohne UI-Latenz aufzulösen.", fr: "Cadres clients compilés conçus pour résoudre les changements d'état sans latence de l'interface." },
      },
      interaction: {
        aiCoreScale: 1.4,
        aiCoreColor: "#ffffff",
        aiCoreShape: "device",
        lightIntensity: 1.4,
        lightColor: "#ffffff",
        particlesCount: 60,
        particlesSpeed: 1.2,
        uiTitle: { en: "SIMULATE INTERACTION.", de: "INTERAKTION SIMULIEREN.", fr: "SIMULER L'INTERACTION." },
        uiSubtitle: { en: "Rotate responsive viewport wireframes to test layout density parameters.", de: "Drehen Sie responsive Viewport-Drahtgitter, um die Layoutdichte-Parameter zu testen.", fr: "Faites pivoter les grilles de la fenêtre pour tester les paramètres de densité." },
      },
      exit: {
        aiCoreScale: 1.1,
        aiCoreColor: "#d5d5d8",
        aiCoreShape: "neural",
        lightIntensity: 1.0,
        lightColor: "#d5d5d8",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "NEURAL MORPHING.", de: "NEURALES MORPHING.", fr: "MORPHISME NEURAL." },
        uiSubtitle: { en: "Rebuilding device chassis into synapse link nodes...", de: "Geräte-Chassis in Synapsen-Verbindungsknoten umbauen...", fr: "Reconfiguration du châssis en nœuds de liaison synaptique..." },
      },
    },
  },
  {
    id: "artificial-intelligence",
    name: "Artificial Intelligence",
    branches: { default: "cloud-infrastructure" },
    states: {
      entry: {
        aiCoreScale: 1.2,
        aiCoreColor: "#ffffff",
        aiCoreShape: "neural",
        lightIntensity: 1.2,
        lightColor: "#ffffff",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "COGNITIVE ARCHITECTURE.", de: "KOGNITIVE ARCHITEKTUR.", fr: "ARCHITECTURE COGNITIVE." },
        uiSubtitle: { en: "Morphing synaptic grids that compute context. We integrate neural structures directly into functional backbones.", de: "Sich verändernde synaptische Gitter, die Kontext berechnen. Wir integrieren neuronale Strukturen direkt in funktionale Backbones.", fr: "Des réseaux synaptiques évolutifs qui calculent le contexte. Nous intégrons les structures neuronales directement dans les architectures." },
      },
      focus: {
        aiCoreScale: 1.4,
        aiCoreColor: "#ffffff",
        aiCoreShape: "neural",
        lightIntensity: 1.4,
        lightColor: "#ffffff",
        particlesCount: 60,
        particlesSpeed: 1.3,
        uiTitle: { en: "SYNAPTIC WEIGHTS.", de: "SYNAPTISCHE GEWICHTE.", fr: "POIDS SYNAPTIQUES." },
        uiSubtitle: { en: "Calibrating distributed tensors and executing context mapping arrays.", de: "Verteilte Tensoren kalibrieren und Kontext-Mapping-Arrays ausführen.", fr: "Calibrage des tenseurs distribués et exécution des réseaux de cartographie contextuelle." },
      },
      interaction: {
        aiCoreScale: 1.6,
        aiCoreColor: "#ffffff",
        aiCoreShape: "neural",
        lightIntensity: 1.6,
        lightColor: "#ffffff",
        particlesCount: 85,
        particlesSpeed: 1.6,
        uiTitle: { en: "TRIGGER INFERENCE.", de: "INFERENZ AUSLÖSEN.", fr: "DÉCLENCHER L'INFÉRENCE." },
        uiSubtitle: { en: "Tap parameters to adjust synaptic weights and filter response profiles.", de: "Tippen Sie auf Parameter, um synaptische Gewichte anzupassen und Antwortprofile zu filtern.", fr: "Modifiez les paramètres pour ajuster les poids synaptiques et filtrer les profils." },
      },
      exit: {
        aiCoreScale: 1.1,
        aiCoreColor: "#e5e5eb",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#e5e5eb",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "CLOUD SHIFT.", de: "CLOUD-ÜBERGANG.", fr: "TRANSITION VERS LE CLOUD." },
        uiSubtitle: { en: "Routing cognitive arrays to distributed compute nodes...", de: "Kognitive Arrays an verteilte Rechenknoten leiten...", fr: "Aiguillage des réseaux cognitifs vers les nœuds de calcul..." },
      },
    },
  },
  {
    id: "cloud-infrastructure",
    name: "Cloud Infrastructure",
    branches: { default: "crm-systems" },
    states: {
      entry: {
        aiCoreScale: 1.1,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.1,
        lightColor: "#ffffff",
        particlesCount: 40,
        particlesSpeed: 1.1,
        uiTitle: { en: "DISTRIBUTED RACKS.", de: "VERTEILTE RACKS.", fr: "RACKS DISTRIBUÉS." },
        uiSubtitle: { en: "High-performance compute clusters optimized for payload delivery. Redundancy built into every node.", de: "Hochleistungs-Compute-Cluster, optimiert für Payload-Auslieferung. Redundanz in jedem Knoten eingebaut.", fr: "Clusters de calcul haute performance optimisés pour la livraison de charge utile. Redondance intégrée dans chaque nœud." },
      },
      focus: {
        aiCoreScale: 1.3,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.3,
        lightColor: "#ffffff",
        particlesCount: 65,
        particlesSpeed: 1.4,
        uiTitle: { en: "ELASTIC PROVISIONING.", de: "ELASTISCHE BEREITSTELLUNG.", fr: "PROVISIONNEMENT ÉLASTIQUE." },
        uiSubtitle: { en: "Server configurations engineered to scale resources dynamically during peak traffic loads.", de: "Serverkonfigurationen, die darauf ausgelegt sind, Ressourcen bei Spitzenlasten dynamisch zu skalieren.", fr: "Configurations serveur conçues pour adapter dynamiquement les ressources lors des pics de charge." },
      },
      interaction: {
        aiCoreScale: 1.5,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.5,
        lightColor: "#ffffff",
        particlesCount: 80,
        particlesSpeed: 1.7,
        uiTitle: { en: "CLUSTER DIAGNOSTICS.", de: "CLUSTER-DIAGNOSE.", fr: "DIAGNOSTIC DE CLUSTER." },
        uiSubtitle: { en: "Query active server nodes to verify payload response latencies.", de: "Fragen Sie aktive Serverknoten ab, um Latenzzeiten für Payloads zu überprüfen.", fr: "Interrogez les nœuds de serveur actifs pour vérifier les temps de latence de réponse." },
      },
      exit: {
        aiCoreScale: 1.1,
        aiCoreColor: "#dddddf",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#dddddf",
        particlesCount: 40,
        particlesSpeed: 1.1,
        uiTitle: { en: "RELATIONAL PATH.", de: "RELATIONALE STRUKTUR.", fr: "AXE RELATIONNEL." },
        uiSubtitle: { en: "Aligning distributed compute arrays with database registry tables...", de: "Ausrichten von verteilten Compute-Arrays an Datenbankregistern...", fr: "Alignement des réseaux de calcul avec les tables du registre..." },
      },
    },
  },
  {
    id: "crm-systems",
    name: "CRM Systems",
    branches: { default: "cyber-security" },
    states: {
      entry: {
        aiCoreScale: 1.1,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.1,
        lightColor: "#ffffff",
        particlesCount: 30,
        particlesSpeed: 0.9,
        uiTitle: { en: "RELATIONAL MAPS.", de: "RELATIONALE KARTEN.", fr: "CARTES RELATIONNELLES." },
        uiSubtitle: { en: "Visualizing customer linkages as interconnected nodes. Streamlining client interactions through unified channels.", de: "Visualisierung von Kundenbeziehungen als miteinander verbundene Knoten. Rationalisierung von Kundeninteraktionen.", fr: "Visualisation des liens clients sous forme de nœuds interconnectés. Simplification des interactions via des canaux unifiés." },
      },
      focus: {
        aiCoreScale: 1.3,
        aiCoreColor: "#f0f0f3",
        aiCoreShape: "sphere",
        lightIntensity: 1.3,
        lightColor: "#f0f0f3",
        particlesCount: 50,
        particlesSpeed: 1.1,
        uiTitle: { en: "SYNCHRONOUS PIPELINES.", de: "SYNCHRONE PIPELINES.", fr: "PIPELINES SYNCHRONES." },
        uiSubtitle: { en: "Data warehouse routing structures designed to maintain profile consistency across nodes.", de: "Data-Warehouse-Routing-Strukturen, die darauf ausgelegt sind, Profilkonsistenz über Knoten hinweg zu wahren.", fr: "Structures de routage pour entrepôts de données conçues pour maintenir la cohérence des profils." },
      },
      interaction: {
        aiCoreScale: 1.5,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.5,
        lightColor: "#ffffff",
        particlesCount: 65,
        particlesSpeed: 1.3,
        uiTitle: { en: "MAP TELEMETRY.", de: "KARTEN-TELEMETRIE.", fr: "TÉLÉMÉTRIE DE LA CARTE." },
        uiSubtitle: { en: "Dissect interconnected client profiles to verify link routing lines.", de: "Analysieren Sie miteinander verbundene Kundenprofile, um Verbindungsroutingleitungen zu überprüfen.", fr: "Analysez les profils clients interconnectés pour vérifier les lignes de routage." },
      },
      exit: {
        aiCoreScale: 1.0,
        aiCoreColor: "#d5d5d8",
        aiCoreShape: "shield",
        lightIntensity: 1.0,
        lightColor: "#d5d5d8",
        particlesCount: 30,
        particlesSpeed: 0.9,
        uiTitle: { en: "SHIELD DEPLOYMENT.", de: "SCHILDAKTIVIERUNG.", fr: "ACTIVATION DU BOUCLIER." },
        uiSubtitle: { en: "Erecting network defenses and encryption barriers...", de: "Netzwerkverteidigung und Verschlüsselungsbarrieren aufbauen...", fr: "Mise en place des défenses réseau et des barrières de chiffrement..." },
      },
    },
  },
  {
    id: "cyber-security",
    name: "Cyber Security",
    branches: { default: "it-infrastructure" },
    states: {
      entry: {
        aiCoreScale: 1.1,
        aiCoreColor: "#ffffff",
        aiCoreShape: "shield",
        lightIntensity: 1.1,
        lightColor: "#ffffff",
        particlesCount: 40,
        particlesSpeed: 1.1,
        uiTitle: { en: "ZERO TRUST SHIELDS.", de: "ZERO TRUST SCHUTZ.", fr: "BOUCLIERS ZERO TRUST." },
        uiSubtitle: { en: "Encrypted firewalls and packet filtering nodes. Protecting infrastructure through absolute isolation.", de: "Verschlüsselte Firewalls und Paketfilterknoten. Schutz der Infrastruktur durch absolute Isolierung.", fr: "Pare-feux cryptés et nœuds de filtrage de paquets. Protection de l'infrastructure par une isolation absolue." },
      },
      focus: {
        aiCoreScale: 1.3,
        aiCoreColor: "#ffffff",
        aiCoreShape: "shield",
        lightIntensity: 1.3,
        lightColor: "#ffffff",
        particlesCount: 60,
        particlesSpeed: 1.4,
        uiTitle: { en: "ENCRYPTED ROUTING.", de: "VERSCHLÜSSELTES ROUTING.", fr: "ROUTAGE CHIFFRÉ." },
        uiSubtitle: { en: "Hardware-level encryption routines designed to sanitize and verify incoming packets.", de: "Verschlüsselungsroutinen auf Hardwareebene, die darauf ausgelegt sind, eingehende Pakete zu bereinigen und zu überprüfen.", fr: "Routines de chiffrement matériel conçues pour assainir et vérifier les paquets entrants." },
      },
      interaction: {
        aiCoreScale: 1.6,
        aiCoreColor: "#ffffff",
        aiCoreShape: "shield",
        lightIntensity: 1.6,
        lightColor: "#ffffff",
        particlesCount: 80,
        particlesSpeed: 1.7,
        uiTitle: { en: "FILTER DIAGNOSTICS.", de: "FILTER-DIAGNOSE.", fr: "DIAGNOSTIC DES FILTRES." },
        uiSubtitle: { en: "Simulate firewall payload injection tests to verify packet rejection latencies.", de: "Simulieren Sie Firewall-Injektionstests, um Paketabweisungslatenzen zu verifizieren.", fr: "Simulez des tests d'injection pour vérifier les temps de rejet des paquets." },
      },
      exit: {
        aiCoreScale: 1.0,
        aiCoreColor: "#e0e0e0",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#e0e0e0",
        particlesCount: 40,
        particlesSpeed: 1.1,
        uiTitle: { en: "BACKBONE ASSEMBLY.", de: "BACKBONE-MONTAGE.", fr: "ASSEMBLAGE DE L'ÉPINE." },
        uiSubtitle: { en: "Deploying structural hardware grids and physical server rack units...", de: "Strukturelle Hardwaregitter und physische Serverrackeinheiten werden aufgebaut...", fr: "Déploiement des grilles matérielles et des racks de serveurs physiques..." },
      },
    },
  },
  {
    id: "it-infrastructure",
    name: "IT Infrastructure",
    branches: { default: "contact" },
    states: {
      entry: {
        aiCoreScale: 1.1,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.1,
        lightColor: "#ffffff",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "THE BACKBONE.", de: "DAS BACKBONE.", fr: "L'ÉPINE DORSALE." },
        uiSubtitle: { en: "Fiber grids, server racks, and network configurations. The physical grounding of the digital ecosystem.", de: "Glasfasernetze, Serverracks und Netzwerkkonfigurationen. Die physische Erdung des digitalen Ökosystems.", fr: "Réseaux de fibres, racks de serveurs et configurations réseau. L'ancrage physique de l'écosystème numérique." },
      },
      focus: {
        aiCoreScale: 1.3,
        aiCoreColor: "#f5f5f7",
        aiCoreShape: "sphere",
        lightIntensity: 1.3,
        lightColor: "#f5f5f7",
        particlesCount: 60,
        particlesSpeed: 1.2,
        uiTitle: { en: "HARDWARE TOPOLOGY.", de: "HARDWARE-TOPOLOGIE.", fr: "TOPOLOGIE MATÉRIELLE." },
        uiSubtitle: { en: "Optic fiber routing rails and high-density copper patches, organized for structural reliability.", de: "Glasfaser-Routingschienen und hochdichte Kupfer-Patches, organisiert für strukturelle Zuverlässigkeit.", fr: "Rails de guidage pour fibres optiques et panneaux de brassage cuivre haute densité." },
      },
      interaction: {
        aiCoreScale: 1.5,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.5,
        lightColor: "#ffffff",
        particlesCount: 75,
        particlesSpeed: 1.5,
        uiTitle: { en: "RACK DIAGNOSTICS.", de: "RACK-DIAGNOSE.", fr: "DIAGNOSTIC DU RACK." },
        uiSubtitle: { en: "Verify patch lane connection paths and measure optical loop speeds live.", de: "Überprüfen Sie Patch-Lane-Verbindungspfade und messen Sie optische Schleifengeschwindigkeiten live.", fr: "Vérifiez les chemins de connexion des baies et mesurez les vitesses de boucle en direct." },
      },
      exit: {
        aiCoreScale: 1.0,
        aiCoreColor: "#dddddf",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#dddddf",
        particlesCount: 40,
        particlesSpeed: 1.0,
        uiTitle: { en: "FEEDBACK DESK.", de: "FEEDBACK-DESK.", fr: "DESCENTE DE CONTACT." },
        uiSubtitle: { en: "Preparing collaboration panels and link terminals...", de: "Kooperationspanels und Verbindungs-Terminals werden vorbereitet...", fr: "Préparation des panneaux de collaboration et des terminaux..." },
      },
    },
  },
  {
    id: "contact",
    name: "Contact Interface",
    branches: { default: "hero" }, // Loop back to Hero on scroll past end
    states: {
      entry: {
        aiCoreScale: 1.0,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#ffffff",
        particlesCount: 30,
        particlesSpeed: 0.7,
        uiTitle: { en: "COLLABORATION DESK.", de: "KOOPERATIONSDESK.", fr: "BUREAU DE COLLABORATION." },
        uiSubtitle: { en: "Ready to design your digital architecture? Connect with our engineering desks to initiate the protocol.", de: "Bereit, Ihre digitale Architektur zu entwerfen? Verbinden Sie sich mit unseren Engineering-Desks.", fr: "Prêt à concevoir votre architecture numérique ? Connectez-vous avec nos bureaux d'études." },
      },
      focus: {
        aiCoreScale: 1.2,
        aiCoreColor: "#f5f5f7",
        aiCoreShape: "sphere",
        lightIntensity: 1.2,
        lightColor: "#f5f5f7",
        particlesCount: 45,
        particlesSpeed: 0.9,
        uiTitle: { en: "SYSTEM SPECIFICATION.", de: "SYSTEM-SPEZIFIKATION.", fr: "SPÉCIFICATIONS DU SYSTÈME." },
        uiSubtitle: { en: "Outlining infrastructure targets and payload volumes before initiating design blueprints.", de: "Infrastrukturziele und Nutzlastvolumina vor der Initiierung von Konstruktionsplänen skizzieren.", fr: "Définition des objectifs d'infrastructure et des volumes de charge utile." },
      },
      interaction: {
        aiCoreScale: 1.3,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.3,
        lightColor: "#ffffff",
        particlesCount: 55,
        particlesSpeed: 1.1,
        uiTitle: { en: "ENGAGE PROTOCOL.", de: "PROTOKOLL AKTIVIEREN.", fr: "ENGAGER LE PROTOCOLE." },
        uiSubtitle: { en: "Click bottom right CTA button to initialize dynamic email connection routing.", de: "Klicken Sie auf den unteren rechten CTA-Button, um das E-Mail-Verbindungslayout zu starten.", fr: "Cliquez sur le bouton CTA en bas à droite pour ouvrir la liaison mail." },
      },
      exit: {
        aiCoreScale: 1.0,
        aiCoreColor: "#ffffff",
        aiCoreShape: "sphere",
        lightIntensity: 1.0,
        lightColor: "#ffffff",
        particlesCount: 30,
        particlesSpeed: 0.7,
        uiTitle: { en: "LOOP PROTOCOL CORE.", de: "PROTOKOLLKERN-SCHLEIFE.", fr: "RETOUR AU NOYAU." },
        uiSubtitle: { en: "Resetting optical coordinates back to intro hero scene...", de: "Optische Koordinaten zurück zur Intro-Hero-Szene zurücksetzen...", fr: "Réinitialisation des coordonnées optiques vers l'écran d'accueil..." },
      },
    },
  },
];
